extends: airbnb
parser: babel-eslint
plugins:
  - react
  - jsx-a11y
  - import
  - react-native
rules:
  no-underscore-dangle: 0
  react/jsx-filename-extension: 0
  react/forbid-prop-types: 1
globals:
  __DEV__: true
  __PROD__: true
  fetch: true
