// USER
export const SET_LOGIN_STATUS = 'SET_LOGIN_STATUS';

// API
export const REQUEST_ALL_GREEKS = 'REQUEST_ALL_GREEKS';
export const RECEIVE_ALL_GREEKS = 'RECEIVE_ALL_GREEKS';
export const RECEIVE_ALL_GREEKS_FAILURE = 'RECEIVE_ALL_GREEKS_FAILURE';
